# Generated by Django 5.1.1 on 2024-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_renewed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='next_renewal',
            field=models.DateTimeField(null=True),
        ),
    ]
