# Generated by Django 5.1.1 on 2024-10-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_last_renewed_alter_order_next_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
