# Generated by Django 5.1.1 on 2024-10-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_email_alter_order_last_renewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
