# Generated by Django 5.1.1 on 2024-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_delete_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
