# Generated by Django 5.1.1 on 2024-10-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_stripe_price_id'),
        ('membership', '0002_membership_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_membership', to='membership.membership'),
        ),
    ]
