# Generated by Django 5.1.1 on 2024-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_membership_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
