# Generated by Django 5.1.1 on 2024-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
