# Generated by Django 5.1.1 on 2024-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_order_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
