# Generated by Django 5.1.1 on 2024-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_membership_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
