# Generated by Django 5.1.1 on 2024-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_order_previous_membership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
